---
- name: Install MariaDB server package, MySQL extension for PHP and PHP MySQL Admin WebUI
  ansible.builtin.apt:
    name: 
    - mariadb-server
    - php-mysql
    state: present

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

# - name: Activate MariaDB server
#   ansible.builtin.shell: sudo mysql_install_db

# - name: Start Mysql Service
#   service: name=mysql state=started enabled=true

# - name: Install python Mysql package        # required for mysql_db tasks below
#   apt: name=python-mysqldb state=present

# - name: Create a new database
#   mysql_db: name=demo state=present collation=utf8_general_ci

# - name: 4. Create a database user
#   mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

# - name: 5a. Copy sample data
#   copy: src=dump.sql dest=/tmp/dump.sql

# - name: 5b. Insert sample data
#   shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: Copy secure SQL template script
  ansible.builtin.template:
    src: mysql_secure_installation.sql
    dest: /tmp/mysql_secure_installation.sql

- name: Execute secure SQL script
  ansible.builtin.shell: mysql -sfu root < /tmp/mysql_secure_installation.sql

# - name: 7. Install Hello World PHP script with database
#   copy: src=db.php dest=/var/www/html/db.php mode=0664
