---
- name: Download the latest version of Wordpress
  ansible.builtin.get_url:
    url: http://wordpress.org/latest.tar.gz
    dest: /tmp/wdlatest.tar.gz

- name: Extract it
  ansible.builtin.unarchive:
    src: /tmp/wdlatest.tar.gz
    dest: /tmp/wordpress
